### PR TITLE
Add an option to compile html string to help user can add html string with their custom directives.

### PR DESCRIPTION
**Pull request by hieutranagi47**
Please take a look at: https://github.com/Templarian/ui.bootstrap.contextMenu/issues/140

### CODE REVIEW

**Comment by pvillaverde** [comment]
Hey there! When will be the next version bump? I did a bower install today and things were not working I had a compile done in my code and with the version I downloaded from bower it it hasn't got the compile funcionality yet!

Thanks! :smile:

**Comment by hieutranagi47** [comment]
Hi Pvillaverde,
You can reference my sample code:
```
{
	html: '<a class="dropdown-item" your-custom-directive>Your label name<a>',
	compile: true,
	click: function () {
		return;
	},
	displayed: function () {
		return ...;
	}
}
```
Hope this help you.

**Comment by pvillaverde** [comment]
Exactly! That was what i meant. I changed computer that day and when installing dependencies I realised that this merge wasn't updated on the bower repos. I'm not sure how they work, but maybe it just needs a version bump so that changes can be seen 🤔

**Comment by hieutranagi47** [comment]
Oh, so weird, you can try run "bower install angular-bootstrap-contextmenu --save" again. I did this way then it works.
My bower json content: "angular-bootstrap-contextmenu": "^1.1.0"

**Comment by pvillaverde** [comment]
I did so, but `contentMenu.js` which comes into /bower_components/angular-bootstrap-contextmenu/contextMenu.js` doesn't have the changes from this merged pull, which includes the compile logic. 

I've just checked if it was a bower issue doing cache, but after cleaning cache it does download the same files from here: https://github.com/Templarian/ui.bootstrap.contextMenu/archive/v1.1.0.tar.gz


```
bower angular-bootstrap-contextmenu#*       not-cached https://github.com/Templarian/ui.bootstrap.contextMenu.git#*
bower angular-bootstrap-contextmenu#*          resolve https://github.com/Templarian/ui.bootstrap.contextMenu.git#*
bower angular-bootstrap-contextmenu#*         download https://github.com/Templarian/ui.bootstrap.contextMenu/archive/v1.1.0.tar.gz
bower angular-bootstrap-contextmenu#*          extract archive.tar.gz
bower angular-bootstrap-contextmenu#*         resolved https://github.com/Templarian/ui.bootstrap.contextMenu.git#1.1.0
bower angular-bootstrap-contextmenu#^1.1.0     install angular-bootstrap-contextmenu#1.1.0

```

Check it creating a folder, doing `bower init` and then `bower install angular-bootstrap-contextmenu --save`

**Comment by hieutranagi47** [comment]
Oh, you are right, I cleaned all cache on my PC, then I reproduced your steps, and I see the same problem with you, although the compilation code is already in the master branch.

**Comment by pvillaverde** [comment]
I've checked docs and added PR #145. It needed version bump and a tag for bower to update.

**Comment by josetaira** [comment]
Version bumped. Apologies for the delays.

**Pull request merged**
