### PR TITLE
fixed #18, created AMD-packed

### LINKED ISSUE #18: Feature: AMD-package
an amd-package-version of your directive would be great
(for usage with an amd package manager like require, http://requirejs.org)

### PR DESCRIPTION
**Pull request by wetternest**
fixed #18
i created an amd-package ready to use with an amd-package-manager (like http://requirejs.org). the package could also be directly used as normal js-resource (untested)

furthermore i created a build.js-file for optimization using r.js (see http://requirejs.org/docs/optimization.html for more details) and added an optimized version (angular-bootstrap-contextmenu.min.js)

### CODE REVIEW

**Comment by Templarian** [comment]
Not sure if I want to modify the source module since it is not really a regular way of handling Angular UI Bootstrap modules. I follow this for all the open source modules I maintain: https://github.com/angular-ui/bootstrap

Do you have an alternative solution?

**Comment by Templarian** [comment]
As for including a minifed library in the repo that is gradually becoming frowned upon. Bower actually put it in their spec 2 years ago for project owners to not include minified scripts / resources. As tooling becomes more common it's _"best"_ to just include the source files.

**Comment by wetternest** [comment]
as my project uses a lot of javascript libraries with many dependencies 
i found that requirejs is a good solution for me. i dont know how other 
angular ui bootstrap modules handle that.
but as this modification is only a few lines of code more and should not 
break the way of "normal inclusion" (sry i had no time to test that yet) 
i think its an enrichment to provide an amd-solution as well

other solutions would be:
     - provide two different versions, one for amd package loader, one 
for direct inclusion
     - use the work-around for non-amd-packages

Am 2015-08-25 um 21:19 schrieb Austin Andrews:

**Comment by Templarian** [comment]
I would be fine including an amd version. Is there a naming convention or a name you would prefer?

**Comment by wetternest** [comment]
i would suggest "angular-bootstrap-contextmenu.amd.js" but i dont know if there is a naming convention. the amd-version should definitly be mentioned in the readme file
please be aware that in the solution i provided is some code that provides support for direct inclusion too, which is unnecessary for an amd-only version!

**Comment by wetternest** [comment]
i also think its easier to maintain with only one version

**Comment by Templarian** [comment]
Assumed, if you want to make a pull request without it I'll just merge that and do a bower update shortly (maybe tonight).

I use https://oclazyload.readme.io/ by the way.

**Comment by wetternest** [comment]
as far as i understand from reading the docs for oclazyload it doent loads dependencies for scripts. the idea of AMD packages is, that all dependencies are defined in the package and thus loaded (including eventually dependencies for this dependencies) in the right order

**Comment by Templarian** [comment]
Correct, not as useful as we just have the individual files listed in the router and let oclazyload take care of loading in the files as the various states are called. This approach generally makes sense because we heavily make use of nested states and modals in most of the apps.

RequireJS seems like overhead for AngularJS applications. Might be useful on smaller apps where everything will eventually be minified together instead of lazy loaded individually.

**Pull request closed without merging**
